/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopbasedpayrollsystem.model;

/**
 *
 * @author Cha
 */
import oopbasedpayrollsystem.dao.EmployeeDatabase;
import oopbasedpayrollsystem.gui.LoginGUI;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperPrintManager;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.JREmptyDataSource;

public class Payslip extends javax.swing.JFrame {
    private String employeeID;
    private Employee employee;
    private EmployeeDatabase employeeDatabase;

    // ✅ Constructor with Employee ID
    public Payslip(String employeeID) {
        this.employeeDatabase = new EmployeeDatabase();
        this.employeeID = employeeID;
        this.employee = employee;

        try {
            int empID = Integer.parseInt(employeeID.trim());
            this.employee = this.employeeDatabase.getEmployeeById(empID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "❌ Invalid Employee ID!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.employee == null) {
            JOptionPane.showMessageDialog(this, "❌ Employee not found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        initComponents();
        loadPayslipData();
    }

    // ✅ Default constructor (for UI editing or previews)
    public Payslip() {
        this.employeeDatabase = new EmployeeDatabase();
        initComponents();
    }

    // ✅ Loads payslip data from the employee object and computes payroll
public void loadPayslipData() {
    if (employee == null) {
        JOptionPane.showMessageDialog(this, "❌ Employee not found!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ✅ Load Basic Details
    txtEmployeeID.setText(String.valueOf(employee.getEmployeeID()));
    txtName.setText(employee.getFullName());
    txtPosition.setText(employee.getPosition());
    txtEmployment.setText(employee.getEmploymentStatus());

    // ✅ Load Salary Breakdown
    txtBasicSalary.setText(String.format("%.2f", employee.getBasicSalary()));
    txtAllowance.setText(String.format("%.2f", employee.getAllowance()));

    // ✅ Compute Gross Salary
    double grossSalary = employee.getBasicSalary() + employee.getAllowance();
    txtGrossSalary.setText(String.format("%.2f", grossSalary));

    // ✅ Load Deductions
    txtSSS.setText(String.format("%.2f", employee.getSssDeduction()));
    txtPhilHealth.setText(String.format("%.2f", employee.getPhilHealthDeduction()));
    txtPagIbig.setText(String.format("%.2f", employee.getPagibigDeduction()));
    txtTax.setText(String.format("%.2f", employee.getBirTax()));

    // ✅ Compute Total Deductions and Net Salary
double totalDeductions = employee.getTotalDeductions();
txtTotalDeductions.setText(String.format("%.2f", totalDeductions));
txtNetSalary.setText(String.format("%.2f", employee.calculateNetSalary()));

    System.out.println("✅ Payslip data loaded for " + employee.getFullName());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblEmployment = new javax.swing.JLabel();
        lblSalaryBreakdown = new javax.swing.JLabel();
        lblDeductions = new javax.swing.JLabel();
        lblBasicSalary = new javax.swing.JLabel();
        lblAllowance = new javax.swing.JLabel();
        lblGrossSalary = new javax.swing.JLabel();
        lblPhilHealth = new javax.swing.JLabel();
        lblSSS = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotalDeductions = new javax.swing.JLabel();
        lblNetSalary = new javax.swing.JLabel();
        lblPagIbig = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        txtEmployment = new javax.swing.JTextField();
        txtBasicSalary = new javax.swing.JTextField();
        txtAllowance = new javax.swing.JTextField();
        txtGrossSalary = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtSSS = new javax.swing.JTextField();
        txtPagIbig = new javax.swing.JTextField();
        txtPhilHealth = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        txtTotalDeductions = new javax.swing.JTextField();
        txtNetSalary = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setText("Name");

        lblEmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmployeeID.setText("Employee ID");

        lblPosition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPosition.setText("Position");

        lblEmployment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmployment.setText("Employment");

        lblSalaryBreakdown.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSalaryBreakdown.setText("Salarty Breakdown");

        lblDeductions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDeductions.setText("Deductions");

        lblBasicSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBasicSalary.setText("Basic Salary");

        lblAllowance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAllowance.setText("Allowance");

        lblGrossSalary.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblGrossSalary.setText("Gross Salary");

        lblPhilHealth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhilHealth.setText("PhilHealth:");

        lblSSS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSSS.setText("SSS:");

        lblTax.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTax.setText("Tax (BIR):");

        lblTotalDeductions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalDeductions.setText("Total Deductions:");

        lblNetSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNetSalary.setText("Net Salary:");

        lblPagIbig.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPagIbig.setText("Pag-ibig:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        txtEmployment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmploymentActionPerformed(evt);
            }
        });

        txtBasicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBasicSalaryActionPerformed(evt);
            }
        });

        txtAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllowanceActionPerformed(evt);
            }
        });

        txtGrossSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrossSalaryActionPerformed(evt);
            }
        });

        txtPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionActionPerformed(evt);
            }
        });

        txtSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSSActionPerformed(evt);
            }
        });

        txtPagIbig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagIbigActionPerformed(evt);
            }
        });

        txtPhilHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhilHealthActionPerformed(evt);
            }
        });

        txtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxActionPerformed(evt);
            }
        });

        txtTotalDeductions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDeductionsActionPerformed(evt);
            }
        });

        txtNetSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetSalaryActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnExit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit1.setText("GENERATE PAYSLIP");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnExit)
                    .addComponent(btnExit1))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        btnExit1.getAccessibleContext().setAccessibleName("GenerateNow");
        btnExit1.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("MotorPH Payroll System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lblSalaryBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(135, 135, 135))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalaryBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed

        
    }//GEN-LAST:event_txtEmployeeIDActionPerformed
private void txtEmployeeIDKeyTyped(java.awt.event.KeyEvent evt) {                                    

}
    private void txtEmploymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmploymentActionPerformed

    }//GEN-LAST:event_txtEmploymentActionPerformed

    private void txtBasicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasicSalaryActionPerformed

    }//GEN-LAST:event_txtBasicSalaryActionPerformed

    private void txtAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllowanceActionPerformed
    
    }//GEN-LAST:event_txtAllowanceActionPerformed

    private void txtGrossSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrossSalaryActionPerformed
    
    }//GEN-LAST:event_txtGrossSalaryActionPerformed

    private void txtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionActionPerformed
     
    }//GEN-LAST:event_txtPositionActionPerformed

    private void txtSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSSActionPerformed
       
    }//GEN-LAST:event_txtSSSActionPerformed

    private void txtPagIbigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagIbigActionPerformed
       
    }//GEN-LAST:event_txtPagIbigActionPerformed

    private void txtPhilHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhilHealthActionPerformed
      
    }//GEN-LAST:event_txtPhilHealthActionPerformed

    private void txtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxActionPerformed
        
    }//GEN-LAST:event_txtTaxActionPerformed

    private void txtTotalDeductionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDeductionsActionPerformed
       
    }//GEN-LAST:event_txtTotalDeductionsActionPerformed

    private void txtNetSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetSalaryActionPerformed
        
    }//GEN-LAST:event_txtNetSalaryActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new LoginGUI().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
if (employee != null) {
        try {
            // Prepare the values using default field names
            Map<String, Object> dataMap = new HashMap<>();
            dataMap.put("field1", employee.getFirstName() + " " + employee.getLastName()); // Full Name
            dataMap.put("field2", employee.getPosition() + " / " + employee.getDepartment()); // Position / Department
            dataMap.put("field3", employee.getMonthlyRate()); // Monthly Rate
            dataMap.put("field4", employee.getDailyRate()); // Daily Rate
            dataMap.put("field5", employee.getDaysWorked()); // Days Worked
            dataMap.put("field6", employee.getOvertimeHours()); // Overtime Hours
            dataMap.put("field7", employee.getGrossSalary()); // Gross Income
            dataMap.put("field8", employee.getRiceSubsidy()); // Rice Subsidy
            dataMap.put("field9", employee.getPhoneAllowance()); // Phone Allowance
            dataMap.put("field10", employee.getClothingAllowance()); // Clothing Allowance
            dataMap.put("field11", employee.getTotalBenefits()); // Total Benefits
            dataMap.put("field12", employee.getSssDeduction()); // SSS
            dataMap.put("field13", employee.getPhilHealthDeduction()); // Philhealth
            dataMap.put("field14", employee.getPagibigDeduction()); // Pagibig
            dataMap.put("field15", employee.getWithholdingTax()); // Withholding Tax
            dataMap.put("field16", employee.getTotalDeductions()); // Total Deductions
            dataMap.put("field17", employee.getTakeHomePay()); // Take Home Pay
            dataMap.put("field18", employee.getPayslipNo());        // Payslip No
            dataMap.put("field19", employee.getEmployeeID());       // Employee ID
            dataMap.put("field20", employee.getPeriodStart());      // Period Start Date
            dataMap.put("field21", employee.getPeriodEnd());    
            
            // Compile and fill the report
            String jrxmlPath = "C:/Users/Seany/Desktop/TEMPORARY STUFF REMEMBER TO ORGANIZE/OOP-main/OOPBasedPayrollSystem/reports/payslip_template2.jrxml";
            JasperReport report = JasperCompileManager.compileReport(jrxmlPath);
            JasperPrint print = JasperFillManager.fillReport(report, dataMap, new JREmptyDataSource());

            // Export to PDF
            String filename = "Payslip_" + employee.getEmployeeID() + ".pdf";
            JasperExportManager.exportReportToPdfFile(print, filename);
            JOptionPane.showMessageDialog(this, "✅ Payslip generated: " + filename);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error generating payslip: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "❌ Employee details are missing.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnExit1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAllowance;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblDeductions;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployment;
    private javax.swing.JLabel lblGrossSalary;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetSalary;
    private javax.swing.JLabel lblPagIbig;
    private javax.swing.JLabel lblPhilHealth;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSSS;
    private javax.swing.JLabel lblSalaryBreakdown;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalDeductions;
    private javax.swing.JTextField txtAllowance;
    private javax.swing.JTextField txtBasicSalary;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployment;
    private javax.swing.JTextField txtGrossSalary;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNetSalary;
    private javax.swing.JTextField txtPagIbig;
    private javax.swing.JTextField txtPhilHealth;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSSS;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotalDeductions;
    // End of variables declaration//GEN-END:variables
}
